### ISSUE TITLE
403 Forbidden Error when intergrate v2 Toneden.loader.js!

### ISSUE THREAD

**Issue by ZhiguoZhang** [ToneDen/toneden-sdk#60]
I am tring use the v2 ToneDen SDK, so I tried the following javascript

        (function() {
            var script = document.createElement("script");

            script.type = "text/javascript";
            script.async = true;
            script.src = "//sd.toneden.io/production/v2/toneden.loader.js"

            var entry = document.getElementsByTagName("script")[0];
            entry.parentNode.insertBefore(script, entry);
        }());

        ToneDenReady = window.ToneDenReady || [];
        ToneDenReady.push(function() {
            ToneDen.configure({
                soundcloudConsumerKey: 'my key'
            });
            // This is where all the action happens:
            ToneDen.player.create({
                dom: "#player",
                eq: "waves",
                skin: "aurora",
                urls: [
                    "a sound cloud list url"
                ]
            });
        });

then I saw the 403 forbidden error, because browser send a request like this:

http://sd.toneden.io/resources/fonts/td-player.woff%27)%20format(%27woff

somehow the javascript is broken. 

so can you help a little bit? thank you!

**Comment by elsbree** [comment]
I'm aware of this issue, it looks like Webpack is somehow sending a request to a malformed font URL. This shouldn't affect the functionality of the player, though. Can you link me to the page where you're seeing this problem?

**Comment by ZhiguoZhang** [comment]
Thank you for reply, please visit our "staging" server: 

    cacb.hoqini.com 

and take a look.

**Comment by ZhiguoZhang** [comment]
and it does affect the functionality of the player, e.g. the scroll bar of playlist, if you click the scroll bar, the browser will direct you to sound cloud page. but not the expect behaviors.

**Comment by dreamdt** [comment]
I remember this, just incorrectly compiled source file
http://sd.toneden.io/production/v2/toneden.js
`font-family:td-player;src:url(\'//sd.toneden.io/resources/fonts/td-player.woff%27)%20format(%27woff\'),`

**Comment by elsbree** [comment]
You're right about the scroll bar not working correctly, but it's not caused by this font loading error. I just fixed the 403 error, so I'm going to close this ticket. I'll create a new one for the scroll bar issue.

**Comment by jackrugile** [comment]
This issue still seems to be happening for me. You can verify in the console of this bare-bones demo here: http://codepen.io/jackrugile/pen/e9ae378f5f46b3b38040107d2c78cd1e

![screen shot 2016-03-03 at 6 00 16 pm](https://cloud.githubusercontent.com/assets/726153/13514880/e8b3d8f8-e169-11e5-9a60-015a2806cf44.png)
